### ISSUE TITLE
The Toshiba AC integration stopped working in Home Assistant 2023.9.1

### ISSUE THREAD

**Issue by q4** [h4de5/home-assistant-toshiba_ac#146]
After upgrading from Home Assistant 2023.7.3 to 2023.9.1 the Toshiba AC integration stopped working.  All entities are marked as "unavailable" (when they are not on the Toshiba app).  I tried re-connecting the Toshiba app by re-entering my credentials, but it made no difference.

What can be done?

**Comment by q4** [comment]
Some additional info:

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:616
Integration: Climate (documentation, issues)
First occurred: 10 September 2023 at 14:11:13 (12 occurrences)
Last logged: 15:55:25

Error adding entities for domain climate with platform toshiba_ac
Error while setting up toshiba_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'account'
```

**Comment by h4de5** [comment]
should be fixed in #135 already - please try to upgrade the installed version of the toshiba integration.

**Comment by h4de5** [comment]
just upgraded to 2023.9.1 without an issue. so will work with the latest version.

**Comment by q4** [comment]
You are right – after upgrading the Toshiba AC integration everything was working again.
Many thanks!
